stages:
  - build
  - linting

build:
  stage: build
  image: python:3.11-slim-bullseye
  before_script:
    - apt-get update && apt-get install -y build-essential gcc  # Install GCC and build tools
    - pip install --upgrade pip setuptools wheel               # Upgrade pip tools
  script:
    - pip install pytest
    - pip install ligo-segments
    - pip install -r requirements.txt
    - pytest -v unit_tests.py

flake8:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script: 
    - flake8 unit_tests.py


