stages:
  - build
  - linting

build:
  stage: build
  image: python:3.11-slim-bullseye
  script:
    - pip install pytest
    - pip install -r requirements.txt
    - pytest -v unit_tests.py

flake8:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script: 
    - flake8 unit_tests.py


